### ISSUE TITLE
Issue: Removing a Tag from a Book

### ISSUE THREAD

**Issue by Matoronto** [WilRBonilla/Pubhub100#1]
Hello,

I'm trying to remove a tag from a book, but when I do so, the webpage returns either an exception or an alternate statement of "There was a problem updating the tag". 

////Declaration of Remove Tag class from Tag Direct Access Object
public boolean RemoveTag(Tag tag);

////Code Statements for Remove Tag Class from Tag Direct Access Object Implementation
	@Override
	public boolean RemoveTag(Tag tag) {
		
		try {
			connection=DAOUtilities.getConnection();
			String Sql = "DELETE FROM book_tags WHERE tags=?";
			stmt = connection.prepareStatement(Sql);
			stmt.setString(1, tag.getIsbn13());
			stmt.setString(2, tag.getTag());
			if(stmt.executeUpdate() != 0)
				return true;
			else
				return false;
			} catch (SQLException e) {
				e.printStackTrace();
				return false;
				
			} finally {
				closeResources();
			}
	}

////Servlets to Remove a Tag from the book
package examples.pubhub.servlets;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import examples.pubhub.model.Book;
import examples.pubhub.model.Tag;
import examples.pubhub.dao.BookDAO;
import examples.pubhub.dao.TagDAO;
import examples.pubhub.utilities.DAOUtilities;

// Servlet implementation class RemoveTagServlet

@WebServlet("/RemoveTag")
public class RemoveTagServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		boolean isSuccess = false;
		
		
		String isbn13 = request.getParameter("isbn13");
		Tag tag = new Tag();
		
		tag.setIsbn13(isbn13);
		tag.setTag(request.getParameter("tag"));
		
		TagDAO dao = DAOUtilities.getTagDAO();
		isSuccess = dao.RemoveTag(tag);
		
		if(isSuccess) {
			request.getSession().setAttribute("message", "Book Tag Successfully Removed.");
			request.getSession().setAttribute("messageClass", "alert-success");
			response.sendRedirect("ViewBookDetails?isbn13=" + isbn13);
		} else {
			request.getSession().setAttribute("message", "There was a problem updating this tag");
			request.getSession().setAttribute("messageClass", "alert-danger");
			request.getRequestDispatcher("bookDetails.jsp").forward(request, response);
		}
	}
}

/////Webpage Code from Book Details Java Server Page to Remove Tag from Book
<section>
     <div class="container">
       <h1><small>Tags</small></h1>
       <table
          class="table table-striped table-hover table-responsive pubhub-datatable">
          <thead>
            <tr>
              <th>Tag</th>
              <td></td>
            </tr>
          </thead>
          
          <tbody>
            <c:forEach var="tag" items="${tags}">
              <tr>
                 <td><c:out value="${tag.tag}"/></td>
                 <td>
                  <form method="post" action="RemoveTag">
                    <input type="hidden" value="${tag.isbn13}" name="isbn13"/>
                    <input type="hidden" value="${tag.tag}" name="tag"/>
                    <button class="btn btn-danger popover-bookpub-removetag" type="submit">Remove Tag</button>
                  </form>
                 </td>
              </tr>
            </c:forEach>
          </tbody>
       </table>
     </div>
   </section>

Here is the results of my code displayed in the picture

![PubHub Error Page for BookDetails](https://user-images.githubusercontent.com/86486701/124002542-dfa59700-d9a3-11eb-9904-29bc07f4ca54.PNG)

**Comment by WilRBonilla** [comment]
Hi, I haven't looked at this in about a year, but I'm guessing something is up with how you're using JDBC:

`		
		String Sql = "DELETE FROM book_tags WHERE tags=?";
		stmt.setString(1, tag.getIsbn13());
		stmt.setString(2, tag.getTag());
		
`

You're setting two parameters in a query that only takes in one and you're sending the ISBN first. I imagine JDBC might throw an exception because of this alone, but even if it doesn't, it will search search for tags = 'someISBN'
